### ISSUE TITLE
Documentation - Record the Web Application Addressing Issue #57

### ISSUE THREAD

**Issue by rkd103** [rkd103/Group-11#59]
### Description ###
* Fixes page redirects to go back to the previous page where appropriate
  * "_When sending a friend request to a locked foreign account, should redirect to locked foreign account.
When making a post/comment/like on foreign timeline, should redirect to foreign timeline.
When making a post/comment on user timeline, should redirect to user timeline.
When clicking button on friends page, should redirect to friends page._"

### Notes ###
**Linked to Issue #57**

**Comment by BrettBaltz** [comment]
https://github.com/rkd103/Group-11/blob/redirect-demo/redirect_demo.mp4
