### ISSUE TITLE
Implement User Story B

### ISSUE THREAD

**Issue by rkd103** [rkd103/Group-11#8]
Taking the User Stories assigned in previous issues, begin brainstorming how to implement the requirements in code.

Namely, perform independent research regarding what packages, techniques, etc. are needed to satisfy the stakeholder's image.

User Story B: "compose, edit, and post statuses on personal timeline"

Original Assignee: HeFeng (ho170)

**Comment by BrettBaltz** [comment]
Split into sub-issues.
